### ISSUE TITLE
想问下搜索的种类好像只有两个了？是您修改了么？

### ISSUE THREAD

**Issue by XuanYuan1122** [roomanl/AndroidMagnetSearch#2]

**Comment by roomanl** [comment]
一直是两个，如果要增加的话，自己可以找一些种子网站加上去。需要加种类直接在rule.json添加即可。rule.json里的爬取规则为xpath语法。熟悉xpath语法的话一看就知道如何修改rule.json。不熟xpath的话，可以自己先去网上了解一下。

**Comment by XuanYuan1122** [comment]
好的 谢谢了
